apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: MySQL
    type: mysql
    access: proxy
    url: mysql:3306
    database: uav_flight
    user: uav
    secureJsonData:
      password: uav123456
    editable: true
