#ifndef __FLIGHT_CONFIG_H__
#define __FLIGHT_CONFIG_H__

#include "types.h"

#define FW_VERSION_MAJOR 1
#define FW_VERSION_MINOR 0
#define FW_VERSION_PATCH 0

#define TASK_ATTITUDE_ESTIMATION_FREQ 500
#define TASK_FLIGHT_CONTROL_FREQ      200
#define TASK_SENSOR_READ_FREQ         1000
#define TASK_MAVLINK_COMM_FREQ        50
#define TASK_MISSION_FREQ             20
#define TASK_FORMATION_FREQ           20
#define TASK_TRACKING_FREQ            20
#define TASK_MOTOR_CONTROL_FREQ       400
#define TASK_HEALTH_MONITOR_FREQ      10
#define TASK_LINK_MANAGER_FREQ        10
#define TASK_THRUST_LEARNER_FREQ      10

#define TASK_ATTITUDE_ESTIMATION_STACK_SIZE 512
#define TASK_FLIGHT_CONTROL_STACK_SIZE      512
#define TASK_SENSOR_READ_STACK_SIZE         256
#define TASK_MAVLINK_COMM_STACK_SIZE        1024
#define TASK_MISSION_STACK_SIZE             512
#define TASK_FORMATION_STACK_SIZE           512
#define TASK_TRACKING_STACK_SIZE            512
#define TASK_MOTOR_CONTROL_STACK_SIZE       256
#define TASK_HEALTH_MONITOR_STACK_SIZE      256
#define TASK_LINK_MANAGER_STACK_SIZE        512
#define TASK_THRUST_LEARNER_STACK_SIZE      512

#define TASK_ATTITUDE_ESTIMATION_PRIORITY 6
#define TASK_FLIGHT_CONTROL_PRIORITY      5
#define TASK_SENSOR_READ_PRIORITY         7
#define TASK_MAVLINK_COMM_PRIORITY        3
#define TASK_MISSION_PRIORITY             4
#define TASK_FORMATION_PRIORITY           4
#define TASK_TRACKING_PRIORITY            4
#define TASK_MOTOR_CONTROL_PRIORITY       5
#define TASK_HEALTH_MONITOR_PRIORITY      2
#define TASK_LINK_MANAGER_PRIORITY        3
#define TASK_THRUST_LEARNER_PRIORITY      3

#define THRUST_LEARNER_MAX_SAMPLES 256
#define THRUST_LEARNER_MIN_WEIGHT_KG 0.5f
#define THRUST_LEARNER_MAX_WEIGHT_KG 25.0f
#define THRUST_LEARNER_DEFAULT_WEIGHT_KG 2.0f
#define THRUST_LEARNER_PID_ADJUST_RATE 0.1f
#define THRUST_LEARNER_GAIN_LIMIT_PCT 50.0f

#define PID_ANGLE_ROLL_P  4.0f
#define PID_ANGLE_ROLL_I  0.02f
#define PID_ANGLE_ROLL_D  0.1f
#define PID_ANGLE_ROLL_I_MAX  15.0f
#define PID_ANGLE_ROLL_OUT_MAX  45.0f

#define PID_ANGLE_PITCH_P  4.0f
#define PID_ANGLE_PITCH_I  0.02f
#define PID_ANGLE_PITCH_D  0.1f
#define PID_ANGLE_PITCH_I_MAX  15.0f
#define PID_ANGLE_PITCH_OUT_MAX  45.0f

#define PID_ANGLE_YAW_P  4.0f
#define PID_ANGLE_YAW_I  0.02f
#define PID_ANGLE_YAW_D  0.1f
#define PID_ANGLE_YAW_I_MAX  15.0f
#define PID_ANGLE_YAW_OUT_MAX  30.0f

#define PID_RATE_ROLL_P  0.15f
#define PID_RATE_ROLL_I  0.05f
#define PID_RATE_ROLL_D  0.001f
#define PID_RATE_ROLL_I_MAX  50.0f
#define PID_RATE_ROLL_OUT_MAX  500.0f

#define PID_RATE_PITCH_P  0.15f
#define PID_RATE_PITCH_I  0.05f
#define PID_RATE_PITCH_D  0.001f
#define PID_RATE_PITCH_I_MAX  50.0f
#define PID_RATE_PITCH_OUT_MAX  500.0f

#define PID_RATE_YAW_P  0.15f
#define PID_RATE_YAW_I  0.05f
#define PID_RATE_YAW_D  0.001f
#define PID_RATE_YAW_I_MAX  50.0f
#define PID_RATE_YAW_OUT_MAX  300.0f

#define PID_ALT_P  1.0f
#define PID_ALT_I  0.1f
#define PID_ALT_D  0.5f
#define PID_ALT_I_MAX  100.0f
#define PID_ALT_OUT_MAX  300.0f

#define PID_POS_X_P  1.0f
#define PID_POS_X_I  0.0f
#define PID_POS_X_D  0.5f
#define PID_POS_X_I_MAX  100.0f
#define PID_POS_X_OUT_MAX  5.0f

#define PID_POS_Y_P  1.0f
#define PID_POS_Y_I  0.0f
#define PID_POS_Y_D  0.5f
#define PID_POS_Y_I_MAX  100.0f
#define PID_POS_Y_OUT_MAX  5.0f

#define IMU_SAMPLE_RATE 1000
#define IMU_GYRO_FSR 2000
#define IMU_ACCEL_FSR 16

#define IMU_GYRO_LSB (16.4f)
#define IMU_ACCEL_LSB (2048.0f)

#define GYRO_BIAS_X -0.005f
#define GYRO_BIAS_Y  0.003f
#define GYRO_BIAS_Z  0.001f

#define ACCEL_BIAS_X 0.01f
#define ACCEL_BIAS_Y 0.02f
#define ACCEL_BIAS_Z -9.81f

#define MPU6050_I2C_ADDR 0x68
#define MAG_I2C_ADDR 0x1E
#define BARO_I2C_ADDR 0x77

#define GPS_UART huart1
#define SBUS_UART huart2
#define MAVLINK_UART huart3

#define MOTOR_PWM_TIM htim1
#define MOTOR1_CHANNEL TIM_CHANNEL_1
#define MOTOR2_CHANNEL TIM_CHANNEL_2
#define MOTOR3_CHANNEL TIM_CHANNEL_3
#define MOTOR4_CHANNEL TIM_CHANNEL_4

#define PWM_MIN 1000
#define PWM_MAX 2000
#define PWM_MID 1500
#define PWM_IDLE 1050
#define PWM_MAX_OUT 1950

#define THROTTLE_MIN 1000
#define THROTTLE_MAX 2000
#define THROTTLE_HOVER 1450

#define SBUS_CHANNEL_MIN 172
#define SBUS_CHANNEL_MAX 1811
#define SBUS_CHANNEL_MID 992

#define SBUS_CHANNEL_ROLL 0
#define SBUS_CHANNEL_PITCH 1
#define SBUS_CHANNEL_THROTTLE 2
#define SBUS_CHANNEL_YAW 3
#define SBUS_CHANNEL_MODE 4
#define SBUS_CHANNEL_ARM 5

#define RC_DEADBAND 30
#define RC_SIGNAL_LOSS_TIMEOUT 1000

#define BATTERY_CELL_COUNT 4
#define BATTERY_CELL_MIN_VOLTAGE 3.2f
#define BATTERY_CELL_MAX_VOLTAGE 4.2f
#define BATTERY_LOW_VOLTAGE 3.5f
#define BATTERY_CRITICAL_VOLTAGE 3.3f
#define BATTERY_FULL_CAPACITY 2200.0f

#define LOW_BATTERY_RTL_TRIGGER_VOLTAGE 14.0f
#define LOW_BATTERY_LAND_TRIGGER_VOLTAGE 13.2f

#define EKF_PROCESS_NOISE_QUAT 0.01f
#define EKF_PROCESS_NOISE_GYRO_BIAS 0.001f
#define EKF_MEASUREMENT_NOISE_ACCEL 0.1f
#define EKF_MEASUREMENT_NOISE_MAG 0.1f

#define MAX_TILT_ANGLE DEG2RAD(45.0f)
#define MAX_YAW_RATE DEG2RAD(180.0f)
#define MAX_CLIMB_RATE 5.0f
#define MAX_DESCEND_RATE 3.0f

#define RTL_ALTITUDE 20.0f
#define LAND_DESCEND_RATE 1.0f
#define TAKEOFF_HEIGHT 5.0f

#define WAYPOINT_ACCEPTANCE_RADIUS 2.0f
#define LOITER_RADIUS 5.0f

#define EARTH_RADIUS 6378137.0f
#define WGS84_A 6378137.0f
#define WGS84_B 6356752.3142f
#define WGS84_E 0.0818191908426f

#define MAVLINK_SYS_ID 1
#define MAVLINK_COMP_ID 1
#define MAVLINK_BAUDRATE 57600

#define LTE_UART_BAUDRATE 115200

#define FILTER_CUTOFF_FREQ 30.0f
#define GYRO_LPF_ALPHA 0.1f
#define ACCEL_LPF_ALPHA 0.1f

#endif
